-- Generated by Tools/naming.py --vectors. Do not edit by hand.
return {
  { key = "Zuflucht", hash = "c5c3b06e7b5a166b" },
  { key = "unsch\195\164tzbarem", hash = "04acd98c92a04c15" },
  { key = "stra\195\159e", hash = "2626f8180f908bb7" },
  { key = "a", hash = "e40c292c4c74b617" },
  { key = "", hash = "811c9dc5040c5b8c" },
  { key = "Weltenwanderer", hash = "0e637510bc40364d" },
  { key = "\195\159", hash = "309e05176233b866" },
  { key = "\195\150l", hash = "ddab0b80bf824047" },
  { key = "\195\156ber", hash = "fb7798afe4411b40" },
  { key = "Kaktus\195\164pfel", hash = "bd516276952d2b1f" },
}
