#!/usr/bin/env python3
"""Assemble the generated audio into installable sound packs.

    python Tools/build_pack.py --size 400

The whole pack does not fit in one addon. The German VoiceOver for Classic is
split into four parts and that is Classic alone; this covers Retail, which is
more than twenty times the quests, plus a clip for every word in the dictionary.

Each part is an addon of its own holding whole shards, and it says which shards
it holds. The engine reads those declarations and knows where to look, so a
player who installs parts one and three gets what those parts cover and silence
for the rest -- rather than an error, or a pack that refuses to work until all
of it is downloaded.

Splitting on shards rather than on a file count is what makes that possible: a
clip's shard is the first part of its own name, so nothing has to ship a list of
which file went where.
"""
import argparse
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
ENGINE = "WordHunterWoW-Voice-DE"
KINDS = {"q": "quest passages", "w": "words"}

TOC = """## Interface: {interface}
## Title: QuestWordHunter - German Voiceover Sounds {number:02d}
## Notes: Sound data for QuestWordHunter German Voiceover. Part {number:02d} of {total:02d}.
## Author: Ironship
## Version: {version}
## Dependencies: {engine}

Part.lua
"""


def shard_sizes(sounds):
    """Every shard that has audio in it, and how much."""
    found = {}
    for kind in KINDS:
        base = sounds / kind
        if not base.is_dir():
            continue
        for shard in sorted(p for p in base.iterdir() if p.is_dir()):
            total = sum(f.stat().st_size for f in shard.rglob("*.ogg"))
            if total:
                found[(kind, shard.name)] = total
    return found


def split(sizes, limit):
    """Whole shards into parts, none larger than the limit if it can be helped.

    Shards are kept in order rather than packed cleverly. A tidy first part that
    holds the low quest ids is worth more to someone downloading only some of it
    than a few megabytes saved.
    """
    parts, current, running = [], [], 0
    for key in sorted(sizes):
        size = sizes[key]
        if current and running + size > limit:
            parts.append(current)
            current, running = [], 0
        current.append(key)
        running += size
    if current:
        parts.append(current)
    return parts


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--sounds", default=str(ROOT / "sounds"))
    ap.add_argument("--out", default=str(ROOT / "build"))
    ap.add_argument("--size", type=float, default=400, help="target part size, MB")
    ap.add_argument("--version", default="0.1.0")
    ap.add_argument("--interface", default="120100")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    sounds = pathlib.Path(args.sounds)
    if not sounds.is_dir():
        sys.exit("no audio at %s -- run Tools/generate.py first" % sounds)
    sizes = shard_sizes(sounds)
    if not sizes:
        sys.exit("no clips found under %s" % sounds)

    parts = split(sizes, args.size * 1024 * 1024)
    total_bytes = sum(sizes.values())
    clips = sum(1 for _ in sounds.rglob("*.ogg"))
    print("%d clips, %.1f GB, %d shards -> %d parts of at most %.0f MB"
          % (clips, total_bytes / 1024 ** 3, len(sizes), len(parts), args.size))

    out = pathlib.Path(args.out)
    for number, shards in enumerate(parts, start=1):
        folder = "%s-Data%02d" % (ENGINE, number)
        held = sum(sizes[k] for k in shards)
        by_kind = {}
        for kind, shard in shards:
            by_kind.setdefault(kind, []).append(shard)
        print("  %-34s %5.0f MB  %s" % (folder, held / 1024 ** 2,
              ", ".join("%d %s shards" % (len(v), k) for k, v in sorted(by_kind.items()))))
        if args.dry_run:
            continue
        target = out / folder
        for kind, shard in shards:
            destination = target / "sounds" / kind / shard
            destination.parent.mkdir(parents=True, exist_ok=True)
            if destination.exists():
                continue
            # Copied, not linked: this is what gets zipped and handed out.
            import shutil
            shutil.copytree(sounds / kind / shard, destination,
                            ignore=shutil.ignore_patterns("*.hash"))
        declaration = ["-- Generated by Tools/build_pack.py. Do not edit by hand.",
                       "WordHunterWoW_Voice_Parts = WordHunterWoW_Voice_Parts or {}",
                       'WordHunterWoW_Voice_Parts["%s"] = {' % folder]
        for kind, shard_list in sorted(by_kind.items()):
            declaration.append('  %s = { %s },'
                               % (kind, ", ".join('"%s"' % s for s in sorted(shard_list))))
        declaration.append("}")
        (target / "Part.lua").write_text("\n".join(declaration) + "\n", encoding="utf-8")
        (target / (folder + "_Mainline.toc")).write_text(
            TOC.format(interface=args.interface, number=number, total=len(parts),
                       version=args.version, engine=ENGINE), encoding="utf-8")
        (target / (folder + "_Vanilla.toc")).write_text(
            TOC.format(interface="11509", number=number, total=len(parts),
                       version=args.version, engine=ENGINE), encoding="utf-8")

    if args.dry_run:
        print("dry run, nothing written")
    else:
        print("wrote %d parts to %s" % (len(parts), out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
