#!/usr/bin/env python3
"""Where a clip lives, decided the same way here and in the addon.

The addon has to find a file without being handed a list of them. A quest line
is easy -- the quest id is a number and the path can be built from it. A word is
not: German keys carry umlauts and the eszett, and a WoW client asked for a path
with those in it does not reliably find the file.

So a word's clip is named after a hash of its key. Both sides compute that hash,
nothing has to ship an index of a hundred thousand filenames, and a clip that
has not been generated yet simply fails to play instead of erroring.

The hash is FNV-1a, twice, because one 32-bit pass is not enough: across 104,000
words a single 32-bit hash is more likely than not to collide, and a collision
means a word plays some other word out loud. Two passes with different seeds are
64 bits, where a collision is a one-in-fifty-thousand event across the whole
pack, and both passes stay inside the 53-bit integers Lua 5.1 can hold exactly.

tests/naming.test.lua checks the two implementations against the same vectors.
Change one and the test fails until the other follows.
"""
import unicodedata

FNV_OFFSET = 0x811C9DC5
FNV_PRIME = 0x01000193
MASK32 = 0xFFFFFFFF

# The three passages an NPC actually says out loud, and the single letter each
# one is filed under. Objectives and the title are read off the screen, not
# spoken by anybody, so they are not here.
SPOKEN_FIELDS = {"description": "o", "progress": "p", "completion": "c"}


def fnv1a32(data, seed=FNV_OFFSET):
    h = seed
    for byte in data:
        h = ((h ^ byte) * FNV_PRIME) & MASK32
    return h


def word_hash(key):
    """Sixty-four bits of hash over the key's UTF-8 bytes, as sixteen hex digits.

    NFC first: "ä" can be written as one code point or as "a" plus a combining
    diaeresis, and the two spell the same word but hash differently. The corpus
    holds both forms because different tools produced it.
    """
    data = unicodedata.normalize("NFC", key).encode("utf-8")
    return "%08x%08x" % (fnv1a32(data), fnv1a32(b"\x01" + data))


def word_path(key):
    """sounds/w/<first two hex digits>/<hash>.ogg"""
    h = word_hash(key)
    return "sounds/w/%s/%s.ogg" % (h[:2], h)


def quest_path(quest_id, field, sentence):
    """sounds/q/<id mod 100, padded>/<id>_<letter><sentence>.ogg

    One clip per sentence, numbered from one in reading order, because the addon
    highlights the sentence it is reading and cannot highlight half of one.

    Sharded so no directory holds more than a few hundred files. Nothing reads
    the shard; it is there so the folder stays openable.
    """
    letter = SPOKEN_FIELDS[field]
    return "sounds/q/%02d/%d_%s%d.ogg" % (int(quest_id) % 100, int(quest_id),
                                          letter, int(sentence))


# Deliberately awkward keys: an umlaut, an eszett, a capital with an umlaut, a
# one-letter word, and the empty string. If the two implementations disagree
# anywhere it will be on one of these.
VECTORS = ["Zuflucht", "unschätzbarem", "straße", "a", "",
           "Weltenwanderer", "ß", "Öl", "Über", "Kaktusäpfel"]


def write_vectors(path):
    """Freeze the expected hashes where the Lua test can read them.

    Committed rather than computed at test time, so a change on either side
    fails: the Lua test reads this file, and check_vectors() reads it back and
    compares against what Python produces now.
    """
    lines = ["-- Generated by Tools/naming.py --vectors. Do not edit by hand.",
             "return {"]
    for key in VECTORS:
        lines.append('  { key = %s, hash = "%s" },'
                     % (lua_quote(key), word_hash(key)))
    lines.append("}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def lua_quote(value):
    """A Lua string literal of the exact bytes, escaped so the file stays ASCII."""
    return '"' + "".join("\\%d" % b if b > 126 or b < 32 or b in (34, 92) else chr(b)
                         for b in value.encode("utf-8")) + '"'


def check_vectors(path):
    text = path.read_text(encoding="utf-8")
    for key in VECTORS:
        expected = '{ key = %s, hash = "%s" },' % (lua_quote(key), word_hash(key))
        if expected not in text:
            return "stale or missing: " + expected
    return None


if __name__ == "__main__":
    import pathlib
    import sys
    here = pathlib.Path(__file__).resolve().parents[1]
    target = here / "tests" / "naming.vectors.lua"
    if "--vectors" in sys.argv:
        write_vectors(target)
        print("wrote", target)
    else:
        problem = check_vectors(target) if target.exists() else "not generated yet"
        print("vectors:", problem or "match")
        print(quest_path(25152, "description", 1), quest_path(8325, "completion", 12))
        print(word_path("Zuflucht"))
        sys.exit(1 if problem else 0)
